### ISSUE TITLE
no output file for more than 10 HP query terms

### ISSUE THREAD

**Issue by vidarmehr** [TheJacksonLaboratory/Phenomiser#37]
@kingmanzhang I am running query command for one of the solved cases (in dichotomy branch) in which the patient has more than 10 HP terms, but I don't get the output file when the number of HP query terms is more than 10.

**Comment by kingmanzhang** [comment]
Is it no output file or output file empty? Could you post the command line argument so that I can try replicate?

**Comment by vidarmehr** [comment]
There is no output file.

query
-da
/Users/ravanv/Documents/IntelliJ_projects/phenomiser/data/phenotype.hpoa
-db
OMIM
-hpo
/Users/ravanv/Documents/IntelliJ_projects/phenomiser/data/hp.obo
-o
/Users/ravanv/Documents/IntelliJ_projects/phenomiser/test.txt
-query
HP:0001263,HP:0000750,HP:0001270,HP:0003508,HP:0000252,HP:0011968,HP:0008676,HP:0010230,HP:0000960,HP:0007441,HP:0000316,HP:0000309,HP:0000457,HP:0000179,HP:0000215,HP:0000293,HP:0000470

**Comment by kingmanzhang** [comment]
It appears we are requesting scoreDistributions for 17 terms (which is wrong--we should request 10). I fixed it (also develop branch. I think you should see the same error in branch as well).

**Comment by vidarmehr** [comment]
Thanks, Aaron. 
Yes. I had the same error in develop branch too.
I ran the code for 5 solved cases, but the results are not good. I think your idea needs to be carefully studied and developed for different cases. I will send you the results through email.
By the way, you can find solved and unsolved cases from
http://stm.sciencemag.org/content/scitransmed/suppl/2014/08/29/6.252.252ra123.DC1/6-252ra123_SM.pdf (Table S4 and Table S5)

**Comment by kingmanzhang** [comment]
Thanks! Let's talk later. 

A different topic, since the query has so many terms, it appears really necessary to turn on the "symmetry" option when calculating similarity scores. @vidarmehr @pnrobinson

**Comment by vidarmehr** [comment]
@kingmanzhang Aaron, just wanted to let you know that I ran phenomizer (dichotomy branch) for the new sets of score distribution files that correspond to the dichotomy and not develop.
