### ISSUE TITLE
Creating phenomiser-cli.jar and docker images for phenomiser

### ISSUE THREAD

**Issue by namratasp20** [TheJacksonLaboratory/Phenomiser#48]
Hi Team,

I have two queries

1) I am facing issues with running the commands after creating a  phenomiser-cli.jar by using  phenomiser-cli directory.
Could you please include the exact steps to be followed to create jar files wherever required ?

2) Is there any plan / ongoing work of releasing a docker image for phenomiser ?

Thanks in advance
Namrata

**Comment by pnrobinson** [comment]
Hi @namratasp20 this project is still in the prototype phase and the supported version of Phenomiser is here
https://compbio.charite.de/phenomizer/
We are not currently planning on releasing a docker image, but if you tell me more about the error message I will see if I can help

**Comment by namratasp20** [comment]
Hi @pnrobinson , thanks for the response. I have gone through the web interface. I want to try and use command line.

jar files needed as per steps on github page
1) phenomiser-cli.jar
2) phenomiserapp.jar

Commands I used to create jar files : 
1) jar cf phenomiser-cli.jar phenomiser-cli/
2) jar cf PhenomiserApp.java 

Error message obtained for cmd -- "java -jar phenomiser-cli.jar precompute -hpo ../hp.obo -da ../phenotype.hpoa --sampling 1 10 [--debug]"

**Error : no main manifest attribute, in phenomiser-cli.jar**  

Same error obtained while executing phenomiserapp.jar

When I do "less <<jar file name>>", I can see a META-INF/MANIFEST.MF
Is there something to be fixed in the manifest or other files ?

**Comment by pnrobinson** [comment]
we usually run jar files with
```
java -jar phenomiser-cli.jar 
```
can you try that?

**Comment by namratasp20** [comment]
hi @pnrobinson,

phenomiser-cli.jar file is not present in current github repository

Hence, I was trying to generate jar file, prior using 'java -jar phenomiser-cli.jar '

Does the team need to add phenomiser-cli.jar file in current branch of repository , as it is missing currently ?

**Comment by pnrobinson** [comment]
We are using maven to build the jar files

simply
```
mvn package
```

**Comment by namratasp20** [comment]
Hi,

Tried with "mvn package"

Its throwing following error:

[INFO] Phenomiser ......................................... SUCCESS [  0.011 s]                                                                                             
[INFO] phenomiser-core .................................... FAILURE [  0.419 s]                                                                                             [INFO] phenomiser-cli ..................................... SKIPPED                                                                                                        
[INFO] ------------------------------------------------------------------------                                                                                             [INFO] BUILD FAILURE                                                                                                                                                        
[INFO] ------------------------------------------------------------------------                                                                                             [INFO] Total time:  0.625 s                                                                                                                                                 
[INFO] Finished at: 2022-01-17T13:02:29+05:30                                                                                                                               [INFO] ------------------------------------------------------------------------                                                                                             **[ERROR] Failed to execute goal on project phenomiser-core: Could not resolve dependencies for project org.jax:phenomiser-core:jar:0.1.1: The following artifacts could not be resolved: org.monarchinitiative.phenol:phenol-core:jar:1.5.1-SNAPSHOT, org.monarchinitiative.phenol:phenol-io:jar:1.5.1-SNAPSHOT, org.monarchinitiative.phenol:phenol-annotations:jar:1.5.1-SNAPSHOT, org.monarchinitiative.phenol:phenol-analysis:jar:1.5.1-SNAPSHOT: Could not find artifact org.monarchinitiative.phenol:phenol-core:jar:1.5.1-SNAPSHOT**

**Comment by pnrobinson** [comment]
@namratasp20 This is not one of the applications that we have actually published (the Phenomizer was published as a webapp) and this repository was made to support another project, but was not independently published. If you want to try to fix this, you could fork this repo and use the latest version of phenol (https://github.com/monarch-initiative/phenol). Phenol also contains code to perform Phenomizer analysis faster than the code in this repo. Probably we will be able to work on this by summer 2022 but this will depend on the pace of a number of other projects. If you would like to work on this project and contribute it back, please let me know and I can give you some more concrete pointers. I am guessing that something like 2-3 weeks of work is required to clean up and test thenew code.

**Comment by namratasp20** [comment]
Changing "<phenol.version>1.5.1-SNAPSHOT</phenol.version>" to "<phenol.version>1.6.3</phenol.version>" resolved the phenol error.
