### ISSUE TITLE
Query option takes too long

### ISSUE THREAD

**Issue by themkdemiiir** [TheJacksonLaboratory/Phenomiser#52]
Hi,

I precomputed both OMIM and ORPHA databases and used the query option for using their cache path separately. However, It took a very long time to get results even though I used ten gb ram for the query. Please give me some suggestions.

Best regards

**Comment by pnrobinson** [comment]
Hi @themkdemiiir the Phenomiser was published in 2009 and we have supported the web-version all this time; unfortunately, the software is starting to show its age. We are planning to re-write the app using a modern web framework but we have no specific funding for this and it is not something we can do right away. We have started to implement routines in https://github.com/monarch-initiative/phenol to make the app faster.
